namespace GenDI.SourceGenerator;

internal static class GenDISourceTemplates
{
    internal const string UsingsWithoutCoverage =
        "using System;\nusing Microsoft.Extensions.DependencyInjection;\n";

    internal const string UsingsWithCoverage =
        "using System;\nusing System.Diagnostics.CodeAnalysis;\nusing Microsoft.Extensions.DependencyInjection;\n";

    internal const string ExcludeFromCodeCoverageAttribute = "[ExcludeFromCodeCoverage]";

    internal const string UnkeyedRegistrationTemplate =
        "        services.Add{0}<{1}>(static serviceProvider => {2});";

    internal const string KeyedRegistrationTemplate =
        "        services.AddKeyed{0}<{1}>({2}, static (serviceProvider, _) => {3});";

    internal const string FileTemplate = """
        // <auto-generated />
        #nullable enable
        {{USINGS}}

        namespace {{NAMESPACE}}.DependencyInjection;

        {{EXCLUDE_FROM_COVERAGE}}public static class GenDIServiceCollectionExtensions
        {
            public static IServiceCollection AddGenDIServices(this IServiceCollection services)
            {
                if (services is null)
                {
                    throw new ArgumentNullException(nameof(services));
                }
        {{REGISTRATIONS}}

                return services;
            }
        }
        """;
}
