<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../pack.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <OutputItemType>Analyzer</OutputItemType>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>$(NoWarn);RS2008;NU5128</NoWarn>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IsPackable>true</IsPackable>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeBundledAnalyzerInPackage</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
      Include="Microsoft.CodeAnalysis.CSharp"
      Version="4.*"
      PrivateAssets="all"
    />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="../GenDI.Analyzers/GenDI.Analyzers.csproj"
      PrivateAssets="all"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="$(OutputPath)$(AssemblyName).dll"
      Pack="true"
      PackagePath="analyzers/dotnet/cs"
      Visible="false"
    />
    <None Include="../../README.md" Pack="true" PackagePath="\" Visible="false" />
    <None Include="../../LICENSE" Pack="true" PackagePath="\" Visible="false" />
    <None Include="../../assets/icon.png" Pack="true" PackagePath="icon.png" Visible="false" />
    <None
      Include="buildTransitive/GenDI.SourceGenerator.props"
      Pack="true"
      PackagePath="buildTransitive/GenDI.SourceGenerator.props"
      Visible="false"
    />
  </ItemGroup>

  <Target Name="IncludeBundledAnalyzerInPackage">
    <MSBuild
      Projects="../GenDI.Analyzers/GenDI.Analyzers.csproj"
      Targets="GetTargetPath"
      Properties="Configuration=$(Configuration);TargetFramework=netstandard2.0"
    >
      <Output TaskParameter="TargetOutputs" ItemName="_BundledAnalyzerTargetPath" />
    </MSBuild>

    <ItemGroup>
      <TfmSpecificPackageFile
        Include="@(_BundledAnalyzerTargetPath)"
        Condition="'%(_BundledAnalyzerTargetPath.Filename)%(_BundledAnalyzerTargetPath.Extension)' == 'GenDI.Analyzers.dll'"
      >
        <PackagePath>analyzers/dotnet/cs</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>
</Project>
