namespace GenDI.SourceGenerator;

internal static class GenDISourceTemplates
{
    internal const string UsingsWithoutCoverage =
        "using System;\nusing System.Threading;\nusing Microsoft.Extensions.DependencyInjection;\n";

    internal const string UsingsWithCoverage =
        "using System;\nusing System.Diagnostics.CodeAnalysis;\nusing System.Threading;\nusing Microsoft.Extensions.DependencyInjection;\n";

    internal const string ExcludeFromCodeCoverageAttribute = "[ExcludeFromCodeCoverage]";

    internal const string UnkeyedRegistrationTemplate =
        "        services.Add{0}<{1}>(static serviceProvider => {2});";

    internal const string KeyedRegistrationTemplate =
        "        services.AddKeyed{0}<{1}>({2}, static (serviceProvider, _) => {3});";

    internal const string ThreadIsolationCacheTemplate =
        "        services.AddKeyed{0}<ThreadLocal<{1}>>({2}, static (serviceProvider, _) => new ThreadLocal<{1}>(() => {3}, trackAllValues: false));";

    internal const string ThreadIsolationUnkeyedAccessTemplate =
        "        services.Add{0}<{1}>(static serviceProvider => serviceProvider.GetRequiredKeyedService<ThreadLocal<{1}>>({2}).Value!);";

    internal const string ThreadIsolationKeyedAccessTemplate =
        "        services.AddKeyed{0}<{1}>({2}, static (serviceProvider, _) => serviceProvider.GetRequiredKeyedService<ThreadLocal<{1}>>({3}).Value!);";

    internal const string ThreadIsolationCacheKeyTemplate = "\"gendi:thread:{0}:{1}:{2}\"";

    internal const string ConditionalRegistrationTemplate = """
                if (
                    string.Equals(Environment.GetEnvironmentVariable("DOTNET_ENVIRONMENT"), "{0}", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"), "{0}", StringComparison.OrdinalIgnoreCase)
                )
                {{
            {1}
                }}
        """;

    internal const string FileTemplate = """
        // <auto-generated />
        {{USINGS}}

        namespace {{NAMESPACE}}.DependencyInjection;

        /// <summary>
        /// Extension methods for registering services discovered by GenDI.
        /// </summary>
        {{EXCLUDE_FROM_COVERAGE}}public static class GenDIServiceCollectionExtensions
        {
            /// <summary>
            /// Registers services discovered by GenDI in the specified <see cref="IServiceCollection"/>.
            /// </summary>
            /// <param name="services">The service collection to add services to.</param>
            /// <returns>The same service collection, for chaining.</returns>
            public static IServiceCollection AddGenDIServices(this IServiceCollection services)
            {
        {{REGISTRATIONS}}

                return services;
            }
        }
        """;
}
