namespace GenDI.SourceGenerator;

internal static class GenDISourceTemplates
{
    internal const string UsingsWithoutCoverage =
        "using System;\nusing Microsoft.Extensions.DependencyInjection;\n";

    internal const string UsingsWithCoverage =
        "using System;\nusing System.Diagnostics.CodeAnalysis;\nusing Microsoft.Extensions.DependencyInjection;\n";

    internal const string ExcludeFromCodeCoverageAttribute = "[ExcludeFromCodeCoverage]";

    internal const string UnkeyedRegistrationTemplate =
        "        services.Add{0}<{1}>(static serviceProvider => {2});";

    internal const string KeyedRegistrationTemplate =
        "        services.AddKeyed{0}<{1}>({2}, static (serviceProvider, _) => {3});";

    internal const string FileTemplate = """
        // <auto-generated />
        {{USINGS}}

        namespace {{NAMESPACE}}.DependencyInjection;

        /// <summary>
        /// Extension methods for registering services discovered by GenDI.
        /// </summary>
        {{EXCLUDE_FROM_COVERAGE}}public static class GenDIServiceCollectionExtensions
        {
            /// <summary>
            /// Registers services discovered by GenDI in the specified <see cref="IServiceCollection"/>.
            /// </summary>
            /// <param name="services">The service collection to add services to.</param>
            /// <returns>The same service collection, for chaining.</returns>
            public static IServiceCollection AddGenDIServices(this IServiceCollection services)
            {
        {{REGISTRATIONS}}

                return services;
            }
        }
        """;
}
